### ISSUE TITLE
FilterError: Program file not found: sass.

### ISSUE THREAD

**Issue by RobertDober** [idank/showthedocs#1]
After installing locally according to the README (just by sudoing `pip install`, do I need virtualenv?) I got this error after visiting `localhost:5000`
```
06:52 % python runserver.py                                                                                                       2017-03-30 06:52:19
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 521-051-914
127.0.0.1 - - [30/Mar/2017 06:52:50] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/robert/git/showthedocs/showdocs/views.py", line 32, in index
    return render_template('index.html')
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/robert/git/showthedocs/showdocs/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/robert/git/showthedocs/showdocs/templates/base.html", line 5, in top-level template code
    {% assets filters="scss", output="showdocs.css", "showdocs.scss" %}
  File "/usr/local/lib/python2.7/dist-packages/webassets/ext/jinja2.py", line 186, in _render_assets
    urls = bundle.urls()
  File "/usr/local/lib/python2.7/dist-packages/webassets/bundle.py", line 806, in urls
    urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/webassets/bundle.py", line 765, in _urls
    *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/webassets/bundle.py", line 619, in _build
    force, disable_cache=disable_cache, extra_filters=extra_filters)
  File "/usr/local/lib/python2.7/dist-packages/webassets/bundle.py", line 543, in _merge_and_apply
    kwargs=item_data)
  File "/usr/local/lib/python2.7/dist-packages/webassets/merge.py", line 276, in apply
    return self._wrap_cache(key, func)
  File "/usr/local/lib/python2.7/dist-packages/webassets/merge.py", line 218, in _wrap_cache
    content = func().getvalue()
  File "/usr/local/lib/python2.7/dist-packages/webassets/merge.py", line 251, in func
    getattr(filter, type)(data, out, **kwargs_final)
  File "/usr/local/lib/python2.7/dist-packages/webassets/filter/sass.py", line 196, in input
    self._apply_sass(_in, out, os.path.dirname(source_path))
  File "/usr/local/lib/python2.7/dist-packages/webassets/filter/sass.py", line 190, in _apply_sass
    return self.subprocess(args, out, _in, cwd=child_cwd)
  File "/usr/local/lib/python2.7/dist-packages/webassets/filter/__init__.py", line 520, in subprocess
    raise FilterError('Program file not found: %s.' % argv[0])
FilterError: Program file not found: sass.
```

**Comment by idank** [comment]
Looks like there's a step missing for installing sass. Can you try following the instructions here to install a command line version? http://sass-lang.com/install

If it works, I'll update the readme.

**Comment by RobertDober** [comment]
I have installed a command line tool, ruby gem sass. I'll double check if I did something stupid (maybe PATH issue with ruby version manager)
